const {chromium}=require('/Users/kiwi/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict'),path=require('node:path'),{pathToFileURL}=require('node:url'),G=require('../model.js');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
const fixture=G.initial();fixture.tutorial='done';fixture.xp=170;fixture.coins=500;for(let i=4;i<8;i++)G.unlock(fixture,i);for(const a of G.animals)G.buy(fixture,'animals',a.id);for(const p of G.plants)fixture.seeds[p.id]=8;for(const d of G.decorations)G.buy(fixture,'decorations',d.id);for(let i=0;i<5;i++)G.plant(fixture,i,G.plants[i].id,Date.now()-40000);G.place(fixture,1,250,600);G.place(fixture,2,350,650);G.place(fixture,3,150,1000);G.place(fixture,4,450,600);G.place(fixture,5,250,1000);
await context.addInitScript(s=>localStorage.setItem('habit-garden-web-v1',JSON.stringify(s)),fixture);await page.goto('http://127.0.0.1:4319');await page.waitForTimeout(500);assert.equal(await page.locator('.plot.ready').count(),5);await page.screenshot({path:path.join(__dirname,'level5-mobile.png')});
// Actual continuous harvest input: pass through each plot twice, each yields exactly once.
await page.locator('#harvestMode').tap();const t=await page.locator('[data-harvest-tool]').boundingBox();await page.mouse.move(t.x+20,t.y+20);await page.mouse.down();for(let i=0;i<5;i++){const p=await page.locator('#plot'+i).boundingBox();await page.mouse.move(p.x+p.width/2,p.y+p.height/2,{steps:4});await page.mouse.move(p.x+p.width/2+1,p.y+p.height/2+1);}await page.mouse.up();assert.equal(await page.evaluate(()=>Object.values(state.harvest).reduce((a,b)=>a+b,0)),5);
await page.locator('[data-action="exit-mode"]').tap();await page.locator('#warehouse').tap();await page.locator('[data-qty="carrot"]').fill('999');assert.equal(await page.locator('[data-qty="carrot"]').inputValue(),'1');assert.ok((await page.locator('.sheet-content').innerText()).includes('最终单价 18'));const coinBefore=await page.evaluate(()=>state.coins);await page.locator('[data-action="sell-all"]').tap();assert.ok((await page.locator('#confirm').innerText()).includes('150'));await page.locator('[data-action="confirm-no"]').tap();assert.equal(await page.evaluate(()=>state.coins),coinBefore);await page.locator('[data-action="sell-all"]').tap();await page.locator('[data-action="confirm-yes"]').tap();assert.equal(await page.evaluate(()=>state.coins),coinBefore+150);
await page.locator('[data-tab="animals"]').tap();await page.locator('[data-action="animal:panda"]').tap();assert.equal(await page.evaluate(()=>Garden.price(state,'carrot')),16);await page.locator('[data-action="animal:panda"]').tap();assert.equal(await page.evaluate(()=>Garden.price(state,'carrot')),18);await page.locator('[data-action="close-modal"]').tap();
// Edit rollback includes animal state; invalid placement leaves original location.
await page.locator('#edit').tap();await page.locator('[data-action="edit-add"]').tap();assert.equal(await page.locator('[data-tab="seeds"]').count(),0);await page.locator('[data-tab="animals"]').tap();await page.locator('[data-action="animal:capybara"]').tap();assert.equal(await page.evaluate(()=>draft.animals.capybara.active),false);await page.locator('[data-action="close-modal"]').tap();await page.locator('[data-action="edit-cancel"]').tap();assert.equal(await page.evaluate(()=>state.animals.capybara.active),true);
// Bounded map gesture and pinch, using Chrome touch input.
const cdp=await context.newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:120,y:380,id:1},{x:240,y:380,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:70,y:380,id:1},{x:290,y:380,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.equal(await page.evaluate(()=>camera.z),1.3);
await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:80,y:320,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:380,y:710,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.equal(await page.evaluate(()=>{const r=document.getElementById('viewport').getBoundingClientRect();return camera.x<=0&&camera.y<=0&&camera.x+750*camera.scale>=r.width-1&&camera.y+1500*camera.scale>=r.height-1}),true);
await page.locator('#settings').tap();await page.locator('[data-action="reset"]').tap();await page.locator('[data-action="confirm-no"]').tap();assert.equal(await page.evaluate(()=>Garden.level(state)),5);await page.locator('[data-action="reset"]').tap();await page.locator('[data-action="confirm-yes"]').tap();assert.equal(await page.evaluate(()=>state.coins),50);assert.equal(await page.evaluate(()=>state.tutorial),'land');assert.equal(await page.evaluate(()=>state.seeds.daisy),4);
assert.deepEqual(errors,[]);
// Standalone file must work with networking fully disabled.
const offline=await browser.newContext({viewport:{width:390,height:844},offline:true});const filePage=await offline.newPage(),fileErrors=[];filePage.on('pageerror',e=>fileErrors.push(e.message));await filePage.goto(pathToFileURL(path.resolve(__dirname,'../习惯花园-双击即玩.html')).href);await filePage.waitForTimeout(600);assert.equal(await filePage.locator('#coins').innerText(),'50');await filePage.locator('#plot0').click();await filePage.locator('#plot0').click();assert.equal(await filePage.evaluate(()=>state.plots[0].plant.duration),3);assert.equal(await filePage.evaluate(()=>[...document.images].filter(i=>!i.complete||!i.naturalWidth).length),0);await filePage.reload();assert.ok(await filePage.evaluate(()=>state.plots[0].plant));assert.deepEqual(fileErrors,[]);await filePage.screenshot({path:path.join(__dirname,'standalone-offline-mobile.png')});
console.log('ADVANCED_OK: five crops; continuous harvest; price and quantity; cancel and reset; touch pinch and pan; offline standalone persistence');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
