const {chromium}=require('/Users/kiwi/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');const path=require('node:path');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});const context=await browser.newContext({viewport:{width:1280,height:960}});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await page.goto('http://127.0.0.1:4319');await page.waitForTimeout(500);await page.screenshot({path:path.join(__dirname,'initial-desktop.png')});console.log('INITIAL',await page.locator('#viewport').boundingBox(),await page.locator('#plot0').boundingBox());
 await page.locator('#plot0').click();assert.equal(await page.evaluate(()=>state.tutorial),'seed');
 // Drag seed through first four plots. Real pointer input, real initial growth clock.
 const seed=await page.locator('[data-seed="daisy"]').boundingBox();await page.mouse.move(seed.x+seed.width/2,seed.y+seed.height/2);await page.mouse.down();
 for(let i=0;i<4;i++){const p=await page.locator('#plot'+i).boundingBox();await page.mouse.move(p.x+p.width/2,p.y+p.height/2,{steps:10});}
 await page.mouse.up();assert.equal(await page.evaluate(()=>state.plots.filter(p=>p.plant).length),4);assert.equal(await page.evaluate(()=>state.seeds.daisy),1);
 await page.waitForTimeout(3300);assert.equal(await page.evaluate(()=>state.tutorial),'harvest');await page.locator('#plot0').click();assert.equal(await page.evaluate(()=>mode),'harvest');
 await page.locator('#plot0').click();assert.equal(await page.evaluate(()=>state.harvest.daisy),1);await page.locator('#warehouse').click();await page.locator('[data-action="sell:daisy"]').click();await page.locator('[data-action="confirm-yes"]').click();assert.equal(await page.evaluate(()=>state.tutorial),'done');assert.equal(await page.evaluate(()=>state.coins),60);
 await page.waitForTimeout(5000);await page.locator('#harvestMode').click();for(let i=1;i<4;i++)await page.locator('#plot'+i).click();await page.waitForTimeout(850);await page.locator('[data-action="confirm-yes"]').click();assert.equal(await page.evaluate(()=>Garden.level(state)),2);assert.equal(await page.evaluate(()=>state.seeds.carrot),1);
 await page.locator('[data-action="exit-mode"]').click();await page.locator('#warehouse').click();await page.locator('[data-action="sell-all"]').click();await page.locator('[data-action="confirm-yes"]').click();await page.locator('[data-action="close-modal"]').click();assert.equal(await page.evaluate(()=>state.coins),90);
 await page.locator('#shop').click();await page.locator('[data-tab="animals"]').click();await page.locator('[data-action="buy:animals:capybara:1"]').click();assert.equal(await page.evaluate(()=>state.animals.capybara.active),true);await page.locator('[data-tab="decorations"]').click();await page.locator('[data-action="buy:decorations:daisy_flowerpot:1"]').click();await page.locator('[data-action="close-modal"]').click();
 await page.locator('#plot4').click();await page.locator('[data-action="confirm-yes"]').click();assert.equal(await page.evaluate(()=>state.plots[4].open),true);
 await page.locator('#warehouse').click();await page.locator('[data-tab="decorations"]').click();await page.locator('[data-action="place-deco:daisy_flowerpot"]').click();assert.equal(await page.evaluate(()=>mode),'edit');
 const dest=await page.evaluate(()=>{const r=document.getElementById('viewport').getBoundingClientRect();return{x:r.left+camera.x+250*camera.scale,y:r.top+camera.y+600*camera.scale};});await page.mouse.click(dest.x,dest.y);assert.equal(await page.evaluate(()=>draft.decorations[0].placed),true);await page.locator('[data-action="edit-confirm"]').click();assert.equal(await page.evaluate(()=>state.decorations[0].placed),true);
 await page.screenshot({path:path.join(__dirname,'level2-desktop.png')});const before=await page.evaluate(()=>JSON.stringify(state));await page.reload();assert.equal(await page.evaluate(()=>JSON.stringify(state)),before);
 await page.locator('#edit').click();const obj=page.locator('[data-object="1"]');await obj.click();await page.locator('[data-action="edit-store"]').click();assert.equal(await page.evaluate(()=>draft.decorations[0].placed),false);await page.locator('[data-action="edit-cancel"]').click();assert.equal(await page.evaluate(()=>state.decorations[0].placed),true);
 await page.setViewportSize({width:390,height:844});await page.waitForTimeout(400);await page.screenshot({path:path.join(__dirname,'level2-mobile.png')});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),390);
 await page.locator('#shop').click();await page.waitForTimeout(350);await page.screenshot({path:path.join(__dirname,'shop-mobile.png')});await page.locator('[data-action="close-modal"]').click();
 // Reload catches offline maturity from saved timestamps.
 await page.locator('#plot0').click();await page.locator('#seedBubble [data-seed=daisy]').click();assert.equal(await page.evaluate(()=>state.plots[0].plant.duration),7);await page.reload();await page.waitForTimeout(7200);assert.equal(await page.evaluate(()=>Garden.stage(state.plots[0].plant).stage),'mature');
 assert.deepEqual(errors,[]);console.log('BROWSER_CORE_FLOW_OK');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
