const {test}=require('node:test');const assert=require('node:assert/strict');const G=require('../model.js');
test('first planting is free, takes 3 seconds, and completes tutorial through sale',()=>{const s=G.initial();assert.equal(s.coins,50);assert.equal(s.seeds.daisy,4);s.tutorial='seed';G.plant(s,0,'daisy',1000);assert.equal(s.seeds.daisy,4);assert.equal(s.plots[0].plant.duration,3);assert.throws(()=>G.harvest(s,0,3999));G.harvest(s,0,4000);assert.equal(s.xp,5);assert.equal(s.tutorial,'warehouse');assert.equal(G.sell(s,'daisy',1),10);assert.equal(s.tutorial,'done');assert.equal(s.coins,60);});
test('all crop times, growth stages, animal boost snapshot and rounded prices match PRD',()=>{const s=G.initial();s.xp=170;s.tutorial='done';s.coins=999;G.buy(s,'animals','capybara');G.buy(s,'animals','panda');assert.deepEqual(G.plants.map(p=>G.growth(s,p.id)),[7,10,15,20,24]);assert.deepEqual(G.plants.map(p=>G.price(s,p.id)),[11,18,26,40,55]);G.plant(s,0,'daisy',1000);G.toggleAnimal(s,'capybara');assert.equal(s.plots[0].plant.duration,7);assert.equal(G.growth(s,'daisy'),8);assert.equal(G.stage(s.plots[0].plant,1000).stage,'seed');assert.equal(G.stage(s.plots[0].plant,3200).stage,'sprout');assert.equal(G.stage(s.plots[0].plant,6000).stage,'growing');assert.equal(G.stage(s.plots[0].plant,8000).stage,'mature');assert.equal(G.stage(s.plots[0].plant,1000000).stage,'mature');G.toggleAnimal(s,'panda');assert.equal(G.price(s,'carrot'),16);});
test('normal economy reaches level 5 without injected money or XP; all land and animals affordable',()=>{const s=G.initial();s.tutorial='seed';let now=1000;G.plant(s,0,'daisy',now);now+=3000;G.harvest(s,0,now);G.sellAll(s);let cycles=0;while(G.level(s)<5){const p=G.plants[G.level(s)-1];for(let i=0;i<4;i++){if(!s.seeds[p.id])G.buy(s,'seeds',p.id);G.plant(s,i,p.id,now);}now+=p.time*1000;for(let i=0;i<4;i++)G.harvest(s,i,now);G.sellAll(s);assert.ok(++cycles<20);}assert.equal(G.level(s),5);for(let i=4;i<8;i++)G.unlock(s,i);for(const a of G.animals)G.buy(s,'animals',a.id);for(const d of G.decorations)G.buy(s,'decorations',d.id);assert.equal(s.plots.filter(p=>p.open).length,8);assert.ok(s.coins>=0);assert.ok(s.animals.capybara.active&&s.animals.panda.active);});
test('unlocks award one seed exactly once; sale clamps quantities and never sells other inventory',()=>{const s=G.initial();s.tutorial='done';for(let i=0;i<4;i++){G.plant(s,i,'daisy',0);G.harvest(s,i,8000);}assert.equal(G.level(s),2);assert.equal(s.seeds.carrot,1);const before=s.seeds.carrot;assert.equal(G.sell(s,'daisy',99),40);assert.equal(s.seeds.carrot,before);assert.throws(()=>G.sell(s,'daisy',-2));assert.throws(()=>G.sellAll(s));assert.equal(s.coins,90);});
test('land must be opened sequentially; invalid transactions do not charge',()=>{const s=G.initial();assert.throws(()=>G.unlock(s,4));assert.equal(s.coins,50);s.xp=170;assert.throws(()=>G.unlock(s,5));G.unlock(s,4);assert.equal(s.coins,35);assert.throws(()=>G.unlock(s,4));assert.throws(()=>G.plant(s,5,'daisy'));assert.throws(()=>G.buy(s,'seeds','pumpkin',2));assert.throws(()=>G.buy(s,'seeds','daisy',-1));assert.equal(s.coins,35);});
test('decoration ownership limits, valid placement, collisions, storing, and edit rollback',()=>{const s=G.initial();s.tutorial='done';G.buy(s,'decorations','daisy_flowerpot',5);assert.throws(()=>G.buy(s,'decorations','daisy_flowerpot'));const draft=G.clone(s);G.place(draft,1,100,600);assert.equal(draft.decorations[0].placed,true);assert.equal(s.decorations[0].placed,false);assert.throws(()=>G.place(draft,2,100,600));assert.throws(()=>G.place(draft,2,G.plotPositions[0].x,G.plotPositions[0].y));assert.throws(()=>G.place(draft,2,20,20));G.store(draft,1);assert.equal(draft.decorations[0].placed,false);});
test('deadlock seeds issued once, only at zero coins, no seed, no plant',()=>{const s=G.initial();s.coins=0;s.seeds.daisy=0;assert.equal(G.rescue(s),true);assert.equal(s.seeds.daisy,2);assert.equal(G.rescue(s),false);s.seeds.daisy=0;s.coins=1;assert.equal(G.rescue(s),false);s.coins=0;s.plots[0].plant={id:'daisy',at:0,duration:8};assert.equal(G.rescue(s),false);});
test('save round trip preserves growth, animals and placed decorations; malformed saves reset',()=>{const s=G.initial();s.tutorial='done';G.plant(s,0,'daisy',1000);G.buy(s,'decorations','daisy_flowerpot');G.place(s,1,100,600);const result=G.load(JSON.stringify(s));assert.equal(result.error,null);assert.deepEqual(result.state,s);assert.equal(G.stage(result.state.plots[0].plant,9000).remaining,0);for(const raw of ['broken','{}','null',JSON.stringify({...s,coins:-1}),JSON.stringify({...s,animals:{}})]){const result=G.load(raw);assert.ok(result.error);assert.deepEqual(result.state,G.initial());}});

test('slanted soil hit areas reject transparent corners and gaps',()=>{for(let i=0;i<8;i++){const p=G.plotPositions[i];assert.equal(G.plotAt(p.x,p.y),i);assert.notEqual(G.plotAt(p.x-79,p.y-47),i);assert.notEqual(G.plotAt(p.x+79,p.y+47),i);}assert.equal(G.plotAt(0,0),-1);});
test('legacy save migration preserves earned progress and moves decorations off new plots',()=>{const s=G.initial();delete s.layoutVersion;s.xp=170;s.coins=123;s.tutorial='done';G.buy(s,'decorations','wooden_bench');s.decorations[0].placed=true;s.decorations[0].x=170;s.decorations[0].y=700;G.plant(s,0,'daisy',1000);const r=G.load(JSON.stringify(s));assert.equal(r.error,null);assert.equal(r.state.coins,s.coins);assert.equal(r.state.xp,170);assert.deepEqual(r.state.plots,s.plots);assert.equal(r.state.layoutVersion,2);const d=r.state.decorations[0];assert.ok(!d.placed||G.validPosition(r.state,d.x,d.y,d.uid));});
